name: Build .exe from Python

on:
  push:
    branches:
      - main  # You can change this to the branch you're working on
  pull_request:
    branches:
      - main  # Trigger when there's a pull request to the main branch

jobs:
  build:
    runs-on: windows-latest  # Choose a Windows environment (needed for .exe)

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # Pull the latest code from your repository

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Replace with your Python version (e.g., 3.10)

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller  # Install PyInstaller to package the Python code

    - name: Create Executable
      run: |
        pyinstaller --onefile --windowed stopwatch.py  # Replace with your script name

    - name: Upload built executable as artifact
      uses: actions/upload-artifact@v2
      with:
        name: stopwatch-executable
        path: dist/stopwatch.exe  # Path to the .exe file generated by PyInstaller

